version: '3'

networks:
    driver:

services:
    currency-service:
        build: .
        restart: always
        ports:
        - '8080:8080'
        networks:
            - driver
        env_file:
            - .env
        depends_on:
            migrate:
                condition: service_completed_successfully

    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        healthcheck:
            test: [
                "CMD-SHELL",
                "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
                ]
            interval: 5s
            retries: 3
        networks:
          - driver

    migrate:
        image: migrate/migrate
        volumes:
            - ./migrations:/migrations
        command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@db:5432/postgres?sslmode=disable", "up"]
        depends_on:
            db:
                condition: service_healthy
        networks:
            - driver
